// src/app/layout.tsx
import type { Metadata } from 'next';
import './globals.css';

/* ---------- UI components ---------- */
import Navbar        from './components/navbar';
import Toup          from './components/toup';
import NextTopLoader from 'nextjs-toploader';

/* ---------- Providers ---------- */
import ReduxProvider     from './providers/ReduxProvider';   // Redux store
import { ThemeProvider } from './context/ThemeContext';     // <-- exact path ✔️

export const metadata: Metadata = {
  title: 'Hello',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen">
        {/* 🔁 Redux Store Provider */}
        <ReduxProvider>
          {/* 🎨 Theme Context Provider */}
          <ThemeProvider>
            {/* ⏫ Page‑load progress bar */}
            <NextTopLoader speed={1000} color="#2196f3" />

            {/* 🧭 Navigation bar */}
            <Navbar />

            {/* 📄 Page content */}
            <main className="pt-16">{children}</main>

            {/* 🔝 Scroll‑to‑top button */}
            <Toup />

            {/* <Footer /> (currently commented) */}
          </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
